apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: todo-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
      annotations:
        rollme: "v1"
    spec:
      containers:
        - name: todo-app
          image: 24112004/todo-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: MONGO_URI

            - name: APP_TITLE
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: APP_TITLE